apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169868150
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169868150
    app.kubernetes.io/part-of: test-app-169868150
  name: java-quarkus-169868150
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169868150
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169868150
    spec:
      containers:
      - image: quay.io/hacdev/gam6vqfc-tenant/test-app-169868150/java-quarkus-169868150@sha256:f2ae415a966b22ac108c7e83e55b7d03fa3c553bc1abdf1aa2913b5d5b6c45f2
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
