apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-169868150
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/gam6vqfc-tenant/test-app-169868150/java-quarkus-169868150@sha256:f2ae415a966b22ac108c7e83e55b7d03fa3c553bc1abdf1aa2913b5d5b6c45f2
        name: my-java-quarkus
        resources: {}
status: {}
